# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-dev
dependencies:
  - python=3.10
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - ffmpeg
  - libsndfile
  - pip:
    - git+https://github.com/m-bain/whisperx.git
    - yt-dlp
    - gradio
    - torch
    - transformers
    - decord
    - pytube @ git+https://github.com/oncename/pytube.git
    - imageio